# installer for the NewNeoWx skin

from weecfg.extension import ExtensionInstaller

def loader():
    return BasicInstaller()

#-------- extension info -----------

VERSION      = "2.2g"
NAME         = 'SguWeewx'
DESCRIPTION  = 'A bespoke skin used to interface the Scottish Gliding Center weather station with the Pilot\'s Wiki'
AUTHOR       = "Sally Woolrich"
AUTHOR_EMAIL = "shunracats<at>gmail.com"

#-------- main loader -----------

class BasicInstaller(ExtensionInstaller):
    def __init__(self):
        super(BasicInstaller, self).__init__(
            version=VERSION,
            name=NAME,
            description=DESCRIPTION,
            author=AUTHOR,
            author_email=AUTHOR_EMAIL,
            config={
                'StdReport': {
                    'NewNeoWx': {
                        'skin': 'NewNeoWx',
                        'enable' : 'True',	# NewNeoWx
                        'HTML_ROOT':'/var/www/html/weewx/NewNeoWx',
                    }
                }
            },
            files=[('skins/NewNeoWx',
                    ['skins/NewNeoWx/almanac.html.tmpl',
                    'skins/NewNeoWx/archive.html.tmpl',
                    'skins/NewNeoWx/footer.inc',
                    'skins/NewNeoWx/graph_area_archive_config.inc',
                    'skins/NewNeoWx/graph_area_config.inc',
                    'skins/NewNeoWx/graph_bar_archive_config.inc',
                    'skins/NewNeoWx/graph_bar_config.inc',
                    'skins/NewNeoWx/graph_radar_config.inc',
                    'skins/NewNeoWx/head.inc',
                    'skins/NewNeoWx/header.inc',
                    'skins/NewNeoWx/index.html.tmpl',
                    'skins/NewNeoWx/js.inc',
                    'skins/NewNeoWx/manifest.json',
                    'skins/NewNeoWx/month-%Y-%m.html.tmpl',
                    'skins/NewNeoWx/month.html.tmpl',
                    'skins/NewNeoWx/skin.conf',
                    'skins/NewNeoWx/telemetry.html.tmpl',
                    'skins/NewNeoWx/week.html.tmpl',
                    'skins/NewNeoWx/year-%Y.html.tmpl',
                    'skins/NewNeoWx/year.html.tmpl',
                    'skins/NewNeoWx/yesterday.html.tmpl',
                    'skins/NewNeoWx/archive/NOAA-%Y.txt.tmpl',
                    'skins/NewNeoWx/archive/NOAA-%Y-%m.txt.tmpl',
                    'skins/NewNeoWx/css/bootstrap.min.css',
                    'skins/NewNeoWx/css/style.min.css',
                    'skins/NewNeoWx/fonts/OFL.txt',
                    'skins/NewNeoWx/fonts/Rubik-Light.eot',
                    'skins/NewNeoWx/fonts/Rubik-Light.woff',
                    'skins/NewNeoWx/fonts/Rubik-Light.woff2',
                    'skins/NewNeoWx/fonts/Rubik-Regular.eot',
                    'skins/NewNeoWx/fonts/Rubik-Regular.woff',
                    'skins/NewNeoWx/fonts/Rubik-Regular.woff2',
                    'skins/NewNeoWx/img/icon-16.ico',
                    'skins/NewNeoWx/img/icon-16.png',
                    'skins/NewNeoWx/img/icon-32.png',
                    'skins/NewNeoWx/img/icon-48.png',
                    'skins/NewNeoWx/img/icon-72.png',
                    'skins/NewNeoWx/img/icon-96.png',
                    'skins/NewNeoWx/img/icon-120.png',
                    'skins/NewNeoWx/img/icon-128.png',
                    'skins/NewNeoWx/img/icon-144.png',
                    'skins/NewNeoWx/img/icon-152.png',
                    'skins/NewNeoWx/img/icon-168.png',
                    'skins/NewNeoWx/img/icon-180.png',
                    'skins/NewNeoWx/img/icon-192.png',
                    'skins/NewNeoWx/img/icon-256.png',
                    'skins/NewNeoWx/img/icon-512.png',
                    'skins/NewNeoWx/img/icon-alpha-1x.png',
                    'skins/NewNeoWx/img/icon-alpha-2x.png',
                    'skins/NewNeoWx/img/splash/splash_640x1136.png',
                    'skins/NewNeoWx/img/splash/splash_750x1334.png',
                    'skins/NewNeoWx/img/splash/splash_828x1792.png',
                    'skins/NewNeoWx/img/splash/splash_1125x2436.png',
                    'skins/NewNeoWx/img/splash/splash_1136x640.png',
                    'skins/NewNeoWx/img/splash/splash_1242x2208.png',
                    'skins/NewNeoWx/img/splash/splash_1242x2688.png',
                    'skins/NewNeoWx/img/splash/splash_1334x750.png',
                    'skins/NewNeoWx/img/splash/splash_1536x2048.png',
                    'skins/NewNeoWx/img/splash/splash_1668x2224.png',
                    'skins/NewNeoWx/img/splash/splash_1668x2388.png',
                    'skins/NewNeoWx/img/splash/splash_1792x828.png',
                    'skins/NewNeoWx/img/splash/splash_2048x1536.png',
                    'skins/NewNeoWx/img/splash/splash_2048x2732.png',
                    'skins/NewNeoWx/img/splash/splash_2208x1242.png',
                    'skins/NewNeoWx/img/splash/splash_2224x1668.png',
                    'skins/NewNeoWx/img/splash/splash_2388x1668.png',
                    'skins/NewNeoWx/img/splash/splash_2436x1125.png',
                    'skins/NewNeoWx/img/splash/splash_2688x1242.png',
                    'skins/NewNeoWx/img/splash/splash_2732x2048.png',
                    'skins/NewNeoWx/js/app.js',
                    'skins/NewNeoWx/js/bootstrap.min.js',
                    'skins/NewNeoWx/js/jquery.min.js',
                    'skins/NewNeoWx/js/mdb.min.js',
                    'skins/NewNeoWx/js/popper.min.js',
                    'skins/NewNeoWx/js/modules/wow.min.js',
                    'skins/NewNeoWx/js/vendor/moment.min.js',
                    'skins/NewNeoWx/js/vendor/moment-with-locales.min.js',
                    'skins/NewNeoWx/js/vendor/apexcharts/apexcharts.min.js',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/ca.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/cs.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/de.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/el.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/en.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/es.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/fi.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/fr.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/he.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/hi.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/hr.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/hy.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/id.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/it.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/ka.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/ko.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/lt.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/nb.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/nl.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/pl.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/pt.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/pt-br.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/rs.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/ru.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/se.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/sk.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/sl.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/sq.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/th.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/tr.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/ua.json',
                    'skins/NewNeoWx/js/vendor/apexcharts/locales/zh-cn.json',
                    'skins/NewNeoWx/weather-icons/css/weather-icons.css',
                    'skins/NewNeoWx/weather-icons/css/weather-icons.min.css',
                    'skins/NewNeoWx/weather-icons/css/weather-icons-wind.css',
                    'skins/NewNeoWx/weather-icons/css/weather-icons-wind.min.css',
                    'skins/NewNeoWx/weather-icons/font/weathericons-regular-webfont.eot',
                    'skins/NewNeoWx/weather-icons/font/weathericons-regular-webfont.svg',
                    'skins/NewNeoWx/weather-icons/font/weathericons-regular-webfont.ttf',
                    'skins/NewNeoWx/weather-icons/font/weathericons-regular-webfont.woff',
                    'skins/NewNeoWx/weather-icons/font/weathericons-regular-webfont.woff2']),
            ]
        )
